from datasheet_ai.models import GeneratedSQL


class LLMAdapter:
    """
    Minimal MVP LLM adapter.

    This first version is intentionally a stub:
    - it does NOT call any real model API
    - it does NOT execute SQL
    - it only returns a few hard-coded SQL examples for testing integration

    This lets us wire the full system first:
    CLI -> QueryService -> LLMAdapter -> Validator -> DB

    Later, this class can be upgraded to call a real LLM provider.
    """

    def generate_sql(self, question: str, schema_context: str) -> GeneratedSQL:
        """
        Translate a natural-language question into SQL.

        Parameters
        ----------
        question : str
            User's natural-language question.
        schema_context : str
            Human-readable description of current database schema.

        Returns
        -------
        GeneratedSQL
            Generated SQL plus explanation, or an error result.

        Notes
        -----
        - This method MUST NOT execute SQL.
        - The returned SQL must still be validated by QueryService.
        """
        normalized_question = question.strip().lower()

        if not normalized_question:
            return GeneratedSQL(
                success=False,
                sql="",
                explanation="",
                error_message="Question is empty.",
            )

        # Simple hard-coded rules for MVP testing.
        # These let us test the NL -> SQL -> Validator -> Execution pipeline.
        if "show all tables" in normalized_question or "list tables" in normalized_question:
            return GeneratedSQL(
                success=True,
                sql="SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%';",
                explanation="List all user-defined tables in the SQLite database.",
                error_message="",
            )

        if "show all students" in normalized_question or "list all students" in normalized_question:
            return GeneratedSQL(
                success=True,
                sql="SELECT * FROM students;",
                explanation="Return all rows from the students table.",
                error_message="",
            )

        if "show all classes" in normalized_question or "list all classes" in normalized_question:
            return GeneratedSQL(
                success=True,
                sql="SELECT * FROM classes;",
                explanation="Return all rows from the classes table.",
                error_message="",
            )

        if "show enrollments" in normalized_question or "list enrollments" in normalized_question:
            return GeneratedSQL(
                success=True,
                sql="SELECT * FROM enrollment;",
                explanation="Return all rows from the enrollment table.",
                error_message="",
            )

        if "show all data" in normalized_question:
            return GeneratedSQL(
                success=True,
                sql="SELECT * FROM students;",
                explanation="Default demo query for showing table data.",
                error_message="",
            )

        # Intentionally imperfect fallback to demonstrate that
        # the system must remain correct even when the LLM is wrong.
        return GeneratedSQL(
            success=True,
            sql="SELECT * FROM unknown_table;",
            explanation=(
                "Fallback SQL generated by the stub adapter. "
                "This is intentionally unsafe/possibly wrong for testing validator behavior."
            ),
            error_message="",
        )