from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class ColumnSchema:
    """
    Represent one column inside a table schema.
    """
    name: str
    dtype: str


@dataclass
class TableSchema:
    """
    Represent the full schema of one database table.

    The columns field stores all column definitions in order.
    """
    table_name: str
    columns: list[ColumnSchema] = field(default_factory=list)


@dataclass
class SchemaMatchResult:
    """
    Store the result of comparing two schemas.

    This is mainly used to tell whether a CSV schema matches
    an existing database table schema.
    """
    is_match: bool
    normalized_csv_columns: list[str] = field(default_factory=list)
    reason: str = ""


@dataclass
class ValidationResult:
    """
    Store the result of SQL validation.
    """
    is_valid: bool
    normalized_sql: str = ""
    error_message: str = ""


@dataclass
class QueryResult:
    """
    Store the result of executing a query.

    On success, this may include returned columns and rows.
    On failure, the error_message field explains what went wrong.
    """
    success: bool
    columns: list[str] = field(default_factory=list)
    rows: list[tuple[Any, ...]] = field(default_factory=list)
    error_message: str = ""
    executed_sql: str = ""


@dataclass
class GeneratedSQL:
    """
    Store the SQL generated by the LLM adapter.

    This keeps both the generated SQL text and any extra explanation
    or error message from the generation step.
    """
    success: bool
    sql: str = ""
    explanation: str = ""
    error_message: str = ""


@dataclass
class CSVLoadResult:
    """
    Store the result of loading CSV data into the database.
    """
    success: bool
    table_name: str = ""
    inserted_rows: int = 0
    created_new_table: bool = False
    error_message: str = ""


@dataclass
class AppError:
    """
    Optional structured error model for future use.

    This is not heavily used right now, but it leaves room
    for cleaner error handling later.
    """
    code: str
    message: str
    details: Optional[str] = None