from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class ColumnSchema:
    """Represents a single column in a table schema."""
    name: str
    dtype: str


@dataclass
class TableSchema:
    """Represents the schema of a database table."""
    table_name: str
    columns: list[ColumnSchema] = field(default_factory=list)


@dataclass
class SchemaMatchResult:
    """Represents the comparison result between two schemas."""
    is_match: bool
    normalized_csv_columns: list[str] = field(default_factory=list)
    reason: str = ""


@dataclass
class ValidationResult:
    """Represents the result of SQL validation."""
    is_valid: bool
    normalized_sql: str = ""
    error_message: str = ""


@dataclass
class QueryResult:
    """Represents the result of a query execution."""
    success: bool
    columns: list[str] = field(default_factory=list)
    rows: list[tuple[Any, ...]] = field(default_factory=list)
    error_message: str = ""
    executed_sql: str = ""


@dataclass
class GeneratedSQL:
    """Represents SQL generated by the LLM adapter."""
    success: bool
    sql: str = ""
    explanation: str = ""
    error_message: str = ""


@dataclass
class CSVLoadResult:
    """Represents the result of loading CSV data into the database."""
    success: bool
    table_name: str = ""
    inserted_rows: int = 0
    created_new_table: bool = False
    error_message: str = ""


@dataclass
class AppError:
    """Optional structured error model for future extension."""
    code: str
    message: str
    details: Optional[str] = None